current:
  - name: 'Aaron Bassett'
    email: 'aaron.bassett@vonage.com'
    twitter: 'aaronbassett'
  - name: 'Alex Lakatos'
    email: 'alex.lakatos@vonage.com'
    twitter: 'lakatos88'  
  - name: 'Amanda Folson'
    email: 'amanda.folson@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'AmbassadorAwsum'  
  - name: 'Chris Guzman'
    email: 'chris.guzman@vonage.com'
    twitter: 'speaktochris'
  - name: 'Eric Giannini'
    email: 'eric.giannini@vonage.com'
    twitter: 'eric_giannini'
  - name: 'Mark Smith'
    email: 'mark.smith@nexmo.com'
    twitter: 'judy2k'  
  - name: 'Michael Heap'
    email: 'michael.heap@vonage.com'
    twitter: 'mheap'      
  - name: 'Olia Dukova'
    email: 'olia.dukova@nexmo.com'
    twitter: 'oliadukova'
    role: 'Community Manager'
  - name: 'Phil Leggetter'
    email: 'phil.leggetter@vonage.com'
    role: 'Director of Developer Relations'
    twitter: 'leggetter'
  - name: 'Rabeb Othmani'
    email: 'rabeb.othmani@vonage.com'
    twitter: 'Rabeb_Othmani'
  - name: 'Sam Machin'
    email: 'sam.machin@nexmo.com'
    twitter: 'sammachin'
  - name: 'Steve Crow'
    email: 'steve.crow@vonage.com'
    twitter: 'cr0wst'
  - name: 'Tony Bedford'
    email: 'tony.bedford@vonage.com'
    role: 'Technical Writer'
alumni:
  - name: 'Adam Butler'
    email: 'adam.butler@vonage.com'
    role: 'Nexmo Developer Technical Lead'
    twitter: 'labfoo'
  - name: 'Tom Morris'
    email: 'tom.morris@vonage.com'
    role: 'Technical Writer'
    twitter: 'tommorris'
